server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: environmental-analyzer
              uri: lb://SERVICIO-ENVIROMENT
              predicates:
                - Path=/api/conjunta/2p/alerts/**
              filters:
                - StripPrefix=3
            - id: notification-dispatcher
              uri: lb://SERVICIO-NOTIFICACIONES
              predicates:
                - Path=/api/conjunta/2p/notifications/**
              filters:
                - StripPrefix=3
            - id: notification-dispatcher
              uri: lb://SERVICIO-NOTIFICACIONES
              predicates:
                - Path=/api/conjunta/2p/notifications/**
              filters:
                - StripPrefix=3
            - id: sensordata-collector
              uri: lb://SERVICIO-SENSORES
              predicates:
                - Path=/api/conjunta/2p/sensor-readings/**
              filters:
                - StripPrefix=3


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-addres: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always