#spring.application.name=ms-publicaciones-repaso

spring:
  application:
    name: SERVICIO-SENSORES
  datasource:
#    url: jdbc:postgresql://localhost:5433/ms_publicacions
#    username: postgres
#    password: postgres
    url: jdbc:postgresql://localhost:26257/sensorDataCollector?user=root&password=
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update #create-drop # Cambia a create-drop para pruebas
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: postgres
    password: postgres
    # Configuración para durabilidad de RabbitMQ
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 5
        multiplier: 2.0
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

server:
#  port: 8081
  port: 0
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-addres: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always